apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: snyk-monitor.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: A Kubernetes Operator for creating and managing Snyk controller instances.
  displayName: Snyk Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - snyk
  - controller
  - monitor
  links:
  - name: Snyk Monitor
    url: https://snyk-monitor.domain
  maturity: alpha
  provider:
    name: Snyk Ltd.
    url: https://snyk.io
  version: 0.0.0
