apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snyk-monitor-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch

# +kubebuilder:scaffold:rules
